language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
before_script: unset GEM_PATH GEM_HOME JRUBY_OPTS
install: ./gradlew assemble
script: ./gradlew -S check && bash test-asciidoctor-upstream.sh
notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#asciidoctor"
