os: linux
dist: trusty
language: java
matrix:
  include:
    - jdk: openjdk11
      dist: xenial
    - jdk: oraclejdk8
    - os: osx

addons:
  hosts:
    - asciidoctorj-builder
  hostname: asciidoctorj-builder
  apt:
    packages:
      - graphviz

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install graphviz; fi

install: ./gradlew -S -Pskip.signing assemble --scan

before_script: unset GEM_PATH GEM_HOME JRUBY_OPTS

script: ./gradlew -S -Pskip.signing check --scan && bash test-asciidoctor-upstream.sh
after_success: if [ "${TRAVIS_BRANCH}" = "master" -a "${TRAVIS_PULL_REQUEST}" = "false" -a "${TRAVIS_JDK_VERSION}" = "oraclejdk8" ]; then ./gradlew clean build artifactoryPublish -x test --scan; fi
notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#asciidoctor"
env:
  - secure: "WYU2AptOM6CIiIykVUCj2Ca4umapAl2Qxv8sQDDTNuv9gVHk1rtU42kD6oqS/YoID0QoPy8g6Ggyvy1MF0wMpL4Vvu8pLnbLiYoJtmecpLHB0UZ1UixsgWL7bHExrh+ciCjjqliN9C0rUnmiDHj9Ald2VSWH6Vvcl2YG67Pbl+c="
