version: '{build}'
skip_tags: true
clone_depth: 10
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
build_script:
  - gradlew.bat -i assemble
test_script:
  - gradlew.bat -i -S check
